Refactored the config and added a template for it

diff --git a/.github/workflows/manage-resources.yaml b/.github/workflows/manage-resources.yaml
--- a/.github/workflows/manage-resources.yaml
+++ b/.github/workflows/manage-resources.yaml
@@ -49,9 +49,9 @@ jobs:
             # -----------------------
             # Extract values using yq
             # -----------------------
-            LITSERVE_IMAGE="$(yq -r '.container.litserve_image' "${CONFIG_PATH}")"
-            S3_BUCKET="$(yq -r '.artifacts.s3_bucket' "${CONFIG_PATH}")"
-            S3_PREFIX="$(yq -r '.artifacts.s3_prefix' "${CONFIG_PATH}")"
+            IMAGE="$(yq -r '.app.container.image' "${CONFIG_PATH}")"
+            S3_BUCKET="$(yq -r '.app.artifacts.s3_bucket' "${CONFIG_PATH}")"
+            S3_PREFIX="$(yq -r '.app.artifacts.s3_prefix' "${CONFIG_PATH}")"
             APP_PORT="$(yq -r '.app.port_mapping.port' "${CONFIG_PATH}")"
             PRIORITY="$(yq -r '.routing.priority' "${CONFIG_PATH}")"
 
@@ -67,9 +67,9 @@ jobs:
             fi
             }
 
-            validate_not_empty "container.litserve_image" "$LITSERVE_IMAGE"
-            validate_not_empty "artifacts.s3_bucket" "$S3_BUCKET"
-            validate_not_empty "artifacts.s3_prefix" "$S3_PREFIX"
+            validate_not_empty "app.container.image" "$IMAGE"
+            validate_not_empty "app.artifacts.s3_bucket" "$S3_BUCKET"
+            validate_not_empty "app.artifacts.s3_prefix" "$S3_PREFIX"
             validate_not_empty "app.port_mapping.port" "$APP_PORT"
             validate_not_empty "routing.priority" "$PRIORITY"
 
@@ -77,7 +77,7 @@ jobs:
             # Additional rule: s3_prefix must NOT start or end with "/"
             # ---------------------------------------------------------
             if [[ "$S3_PREFIX" == /* || "$S3_PREFIX" == */ ]]; then
-            echo "ERROR: artifacts.s3_prefix cannot start or end with '/': ${S3_PREFIX}" >&2
+            echo "ERROR: app.artifacts.s3_prefix cannot start or end with '/': ${S3_PREFIX}" >&2
             exit 1
             fi
 
@@ -87,7 +87,7 @@ jobs:
             {
             echo "action=${ACTION}"
             echo "config_path=${CONFIG_PATH}"
-            echo "litserve_image=${LITSERVE_IMAGE}" # Docker image for the application
+            echo "image=${IMAGE}"                   # Docker image for the application
             echo "s3_bucket=${S3_BUCKET}"           # S3 bucket where artifacts for different ml models are located
             echo "s3_prefix=${S3_PREFIX}"           # S3 prefix where a model's artifact is located 
             echo "app_port=${APP_PORT}"             # Docker port to map on localhost
@@ -118,7 +118,7 @@ jobs:
             set -euo pipefail
 
             PREFIX="${{ steps.parse.outputs.prefix }}"
-            LITSERVE_IMAGE="${{ steps.parse.outputs.litserve_image }}"
+            IMAGE="${{ steps.parse.outputs.image }}"
             S3_BUCKET="${{ steps.parse.outputs.s3_bucket }}"
             S3_PREFIX="${{ steps.parse.outputs.s3_prefix }}"
             PRIORITY="${{ steps.parse.outputs.priority }}"
@@ -136,7 +136,7 @@ jobs:
             "${ECS_CLUSTER_ID}" \
             "${SUBNETS_CSV}" \
             "${AWS_REGION}" \
-            "${LITSERVE_IMAGE}"
+            "${IMAGE}"
             
         - name: Destroy resources
           if: steps.parse.outputs.action == 'destroy'
